name: Java CI with Gradle

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. 기본 체크아웃
    - name: Checkout
      uses: actions/checkout@v3

    # 2. Gradlew 실행 허용 
    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew

    # 3. JDK 17로 세팅
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17' # 11 -> 17
        distribution: 'temurin'

    # 4. application.properties 생성
    - name: Create application.properties
      run: |
        echo "Creating application.properties"
        mkdir -p ./src/main/resources 
        echo "${{ secrets.ENV }}" > ./src/main/resources/application.properties
      shell: bash

    # 5. [수정] Gradle build (Test 포함, 액션 버전 v3로 업그레이드)
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v3 # v3로 버전 업
      with:
        arguments: clean build # '-x test' 제거 (이제 테스트가 실행됩니다)
